INSERT INTO Crypto (symbol, description, name) VALUES
('BTC', 'De eerste, bekendste cryptomunt.', 'Bitcoin'),
('ETH', 'Een cryptomunt.', 'Ethereum'),
('ADA', 'Een cryptomunt.', 'Cardano'),
('BNB', 'Een cryptomunt.', 'Binance Coin'),
('USDT', 'Een 1 op 1 aan de dollar gelinkte cryptomunt.', 'Tether'),
('XRP', 'Een cryptomunt.', 'XRP'),
('DOGE', 'Een cryptomunt.', 'Dogecoin'),
('SOL', 'Een cryptomunt.', 'Solana'),
('DOT', 'Een cryptomunt.', 'Polkadot'),
('USDC', 'Een 1 op 1 aan de dollar gelinkte cryptomunt.', 'USD Coin'),
('UNI', 'Een cryptomunt.', 'Uniswap'),
('LINK', 'Een cryptomunt.', 'Chainlink'),
('LUNA', 'Een cryptomunt.', 'Terra'),
('BCH', 'Een cryptomunt.', 'Bitcoin Cash'),
('BUSD', 'Een 1 op 1 aan de dollar gelinkte cryptomunt.', 'Binance USD'),
('LTC', 'Een cryptomunt.', 'Litecoin'),
('ICP', 'Een cryptomunt.', 'Internet Computer'),
('WBTC', 'Een cryptomunt.', 'Wrapped Bitcoin'),
('MATIC', 'Een cryptomunt.', 'Polygon'),
('VET', 'Een cryptomunt.', 'VeChain'),
('ETC', 'Een cryptomunt.', 'Ethereum Classic'),
('XLM', 'Een cryptomunt.', 'Stellar'),
('AVAX', 'Een cryptomunt.', 'Avalanche'),
('FIL', 'Een cryptomunt.', 'Filecoin'),
('TRX', 'Een cryptomunt.', 'Tron'),
('THETA', 'Een cryptomunt.', 'Theta'),
('DAI', 'Een cryptomunt.', 'Dai'),
('FTT', 'Een cryptomunt.', 'FTX Token'),
('XMR', 'Een cryptomunt.', 'Monero'),
('ATOM', 'Een cryptomunt.', 'Cosmos');